### PR TITLE
For #463: Fixed LifeSteal bug

### LINKED ISSUE #463: Bug: StealLife effect does not heal the amount of damage dealt.
It must know how much damage was actually dealt in the resolved attack. 

Size: 1 unit

### PR DESCRIPTION
**Pull request by paulodamaso**
Closes #463 
- Created `Damage` concept: represents damage dealt to some character. It calculates the damage according target and source
- Created `PhysicalDamage` which holds the calculation of physical damage,which includes armor value
- Fixed tests for `PhysicalDamage` using the new concepts
- Used the `Caculate` method from `Damage`  to get the correct amount of damage to be healed on `LifeSteal`

### CODE REVIEW

File: src/ProjectNeon/Assets/Features/Effects/DamageApplied.cs [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+    private Damage _damage;
+
+    public DamageApplied(Damage damage)
+    {
+        _damage = damage;
+    }
+
+    public void Apply(Member source, Target target)
+    {
+        target.Members[0].State.ChangeHp(-_damage.Calculate(source, target) * target.Members[0].State.Damagability());
```
Comment (SilasReinagel) [inline src/ProjectNeon/Assets/Features/Effects/DamageApplied.cs]: This members indexing hack is getting insane.

We can't add more bugs to the system.

No more indexing into Target.

File: src/ProjectNeon/Assets/Features/Effects/AllEffects.cs [hunk 2]
```diff
@@ -8,7 +8,7 @@ public static class AllEffects
     {
         { EffectType.Nothing, e => new NoEffect() },
         { EffectType.HealFlat, e => new SimpleEffect(m => m.GainHp(e.IntAmount))},
-        { EffectType.PhysicalDamage, e => new PhysicalDamage(e.IntAmount) },
+        { EffectType.PhysicalDamage, e => new DamageApplied(new PhysicalDamage(e.IntAmount)) },
```
Comment (SilasReinagel) [inline src/ProjectNeon/Assets/Features/Effects/AllEffects.cs]: `e.IntAmount` is wrong for a multiplier. All multipliers are floats.

File: src/ProjectNeon/Assets/Features/Effects/PhysicalDamage.cs [hunk 3]
```diff
@@ -1,17 +1,17 @@
...
     {
         Multiplier = multiplier;
     }
 
-    public void Apply(Member source, Target target)
+    public int Calculate(Member source, Target target)
     {
-        Damage = source.State.Attack() * Multiplier;
-        target.Members[0].State.TakePhysicalDamage(source.State.Attack() * Multiplier);
+        return Convert.ToInt32(source.State.Attack() * Multiplier * ((1f - target.Members[0].State.Armor()) / 1f));
```
Comment (SilasReinagel) [inline src/ProjectNeon/Assets/Features/Effects/PhysicalDamage.cs]: No direct conversions to `ints`. Should be explicitly rounded up. Should be in a shared method.

File: src/ProjectNeon/Assets/Z_Tests/Features/Effects/StealLifeOnAttackTests.cs [hunk 4]
```diff
@@ -18,8 +18,8 @@ public void StealLifeOnAttack_ApplyEffect_LifeIsStolenCorrectly()
         attacker.State.TakeRawDamage(6);
 
         AllEffects.Apply(StealLifeOnAttack(), caster, new MemberAsTarget(attacker));
-        new Attack(5).Apply(attacker, target);
+        new Attack(1).Apply(attacker, target);
```
Comment (SilasReinagel) [inline src/ProjectNeon/Assets/Z_Tests/Features/Effects/StealLifeOnAttackTests.cs]: I don't understand these numbers. Why are they randomly changed?

File: src/ProjectNeon/Assets/Features/Effects/DamageApplied.cs (hunk 1 above)
Comment (paulodamaso) [reply src/ProjectNeon/Assets/Features/Effects/DamageApplied.cs]: @SilasReinagel It will be fixed in #460

File: src/ProjectNeon/Assets/Features/Effects/AllEffects.cs (hunk 2 above)
Comment (paulodamaso) [reply src/ProjectNeon/Assets/Features/Effects/AllEffects.cs]: @SilasReinagel My bad sorry. Fixed

File: src/ProjectNeon/Assets/Features/Effects/DamageApplied.cs (hunk 1 above)
Comment (paulodamaso) [reply src/ProjectNeon/Assets/Features/Effects/DamageApplied.cs]: @SilasReinagel It will be fixed in #460

File: src/ProjectNeon/Assets/Features/Effects/PhysicalDamage.cs (hunk 3 above)
Comment (paulodamaso) [reply src/ProjectNeon/Assets/Features/Effects/PhysicalDamage.cs]: @SilasReinagel Made just like other rouding operations in the code, please take a look

File: src/ProjectNeon/Assets/Z_Tests/Features/Effects/StealLifeOnAttackTests.cs (hunk 4 above)
Comment (paulodamaso) [reply src/ProjectNeon/Assets/Z_Tests/Features/Effects/StealLifeOnAttackTests.cs]: @SilasReinagel Reverted them to the previous values. Just forgot to remove a different test case

File: src/ProjectNeon/Assets/Features/Effects/PhysicalDamage.cs [hunk 5]
```diff
@@ -1,17 +1,17 @@
...
     {
         Multiplier = multiplier;
     }
 
-    public void Apply(Member source, Target target)
+    public int Calculate(Member source, Target target)
     {
-        Damage = source.State.Attack() * Multiplier;
-        target.Members[0].State.TakePhysicalDamage(source.State.Attack() * Multiplier);
+        return Convert.ToInt32(Math.Ceiling(source.State.Attack() * Multiplier * ((1f - target.Members[0].State.Armor()) / 1f)));
```
Comment (SilasReinagel) [inline src/ProjectNeon/Assets/Features/Effects/PhysicalDamage.cs]: Still, no manual conversions in these classes. 

This is duplicate math code.

File: src/ProjectNeon/Assets/Features/Effects/DamageApplied.cs [hunk 6]
```diff
@@ -0,0 +1,14 @@
+﻿public sealed class DamageApplied : Effect
```
Comment (SilasReinagel) [inline src/ProjectNeon/Assets/Features/Effects/DamageApplied.cs]: Cannot be a past-tense verb yet. When this is created it hasn't happened.

File: src/ProjectNeon/Assets/Features/Effects/AllEffects.cs (hunk 2 above)
Comment (SilasReinagel) [reply src/ProjectNeon/Assets/Features/Effects/AllEffects.cs]: This still isn't fixed.

File: src/ProjectNeon/Assets/Features/Effects/PhysicalDamage.cs (hunk 5 above)
Comment (paulodamaso) [reply src/ProjectNeon/Assets/Features/Effects/PhysicalDamage.cs]: @SilasReinagel Used unity's `Mathf.CeilToInt` to solve it

File: src/ProjectNeon/Assets/Features/Effects/DamageApplied.cs (hunk 6 above)
Comment (paulodamaso) [reply src/ProjectNeon/Assets/Features/Effects/DamageApplied.cs]: @SilasReinagel Made some renaming on `Damage` constructs
